apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlp-app-deploy
  labels:
    app: nlp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nlp-app
  template:
    metadata:
      labels:
        app: nlp-app
    spec:
      containers:
      - name: app
        imagePullPolicy: Never
        image: nlp-app
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /data
          name: test-volume
      volumes:
        - name: test-volume
          hostPath:
            # directory location on host
            path: /data
---
apiVersion: v1
kind: Service
metadata:
  name: nlp-app-svc
spec:
  type: NodePort
  selector:
    app: nlp-app
  ports:
  - name: nlp-app-port
    protocol: TCP
    port: 8080
    targetPort: 8080
